/**
 * The Kineris product catalogue: the 16 peptides with their real sizes and prices
 * (supplied by Harvey, October 2026), plus two lab-supply entries.
 *
 * The two LAB_SUPPLY_CATALOGUE entries are NOT confirmed: they are left over from the
 * placeholder list (pack section 7 mentions 2 lab supplies, but their names/sizes never
 * survived the paste), have no product photography and use placeholder pricing in seed.ts.
 * Replace or remove them once the real lab-supply list is known.
 *
 * Per-product technical data (CAS numbers, molecular formula/weight, purity) is still
 * placeholder, generated by `apps/backend/prisma/seed.ts`, see docs/PROJECT_NOTES.md.
 *
 * `slug` + size are also the keys of the product images in `apps/web/public/products/`
 * (`<slug>-<size>.webp`, built by `tools/product-shots/`), keep them in sync with
 * `tools/product-shots/products.json`.
 *
 * PT-141 is included since the pack's own text discusses it as part of the range (with its
 * own flag: "has a strong human-use association... OPEN: whether it stays in the launch
 * range"), pending that same decision.
 */

export interface CatalogueEntry {
  slug: string
  name: string
  category: 'peptide' | 'lab-supply'
  sizes: string[]
  /** Alternative names, shown as "Also known as" on the product page. */
  synonyms?: string[]
  /** Price in pence per size, same order as `sizes`. Seed falls back to placeholder pricing when omitted. */
  pricesMinorUnits?: number[]
}

export const PEPTIDE_CATALOGUE: CatalogueEntry[] = [
  { slug: 'bpc-157', name: 'BPC-157', category: 'peptide', sizes: ['5mg', '10mg'], pricesMinorUnits: [1695, 2995] },
  {
    slug: 'tb-500',
    name: 'TB-500',
    category: 'peptide',
    sizes: ['2mg', '5mg'],
    synonyms: ['Thymosin Beta-4 acetate'],
    pricesMinorUnits: [1595, 2995],
  },
  {
    slug: 'ghk-cu',
    name: 'GHK-Cu',
    category: 'peptide',
    sizes: ['50mg'],
    synonyms: ['Copper peptide'],
    pricesMinorUnits: [2495],
  },
  {
    slug: 'cjc-1295-no-dac',
    name: 'CJC-1295 (no DAC)',
    category: 'peptide',
    sizes: ['5mg'],
    synonyms: ['Mod GRF 1-29'],
    pricesMinorUnits: [2495],
  },
  { slug: 'ipamorelin', name: 'Ipamorelin', category: 'peptide', sizes: ['5mg'], pricesMinorUnits: [1995] },
  {
    slug: 'sermorelin',
    name: 'Sermorelin',
    category: 'peptide',
    sizes: ['5mg'],
    synonyms: ['Sermorelin acetate'],
    pricesMinorUnits: [2795],
  },
  {
    slug: 'tesamorelin',
    name: 'Tesamorelin',
    category: 'peptide',
    sizes: ['2mg', '10mg'],
    pricesMinorUnits: [2795, 5495],
  },
  { slug: 'igf-1-lr3', name: 'IGF-1 LR3', category: 'peptide', sizes: ['1mg'], pricesMinorUnits: [5495] },
  { slug: 'mots-c', name: 'MOTS-c', category: 'peptide', sizes: ['10mg'], pricesMinorUnits: [2995] },
  { slug: 'nad-plus', name: 'NAD+', category: 'peptide', sizes: ['500mg'], pricesMinorUnits: [5995] },
  { slug: 'epitalon', name: 'Epitalon', category: 'peptide', sizes: ['10mg'], pricesMinorUnits: [1950] },
  { slug: 'selank', name: 'Selank', category: 'peptide', sizes: ['5mg'], pricesMinorUnits: [1595] },
  { slug: 'semax', name: 'Semax', category: 'peptide', sizes: ['5mg'], pricesMinorUnits: [1895] },
  { slug: 'dsip', name: 'DSIP', category: 'peptide', sizes: ['5mg'], pricesMinorUnits: [1395] },
  { slug: 'thymosin-alpha-1', name: 'Thymosin Alpha-1', category: 'peptide', sizes: ['5mg'], pricesMinorUnits: [2995] },
  {
    slug: 'pt-141',
    name: 'PT-141',
    category: 'peptide',
    sizes: ['10mg'],
    synonyms: ['Bremelanotide'],
    pricesMinorUnits: [2095],
  },
]

export const LAB_SUPPLY_CATALOGUE: CatalogueEntry[] = [
  { slug: 'bacteriostatic-water', name: 'Bacteriostatic Water', category: 'lab-supply', sizes: ['10ml', '30ml'] },
  { slug: 'sterile-filters', name: 'Sterile Filters (0.22µm)', category: 'lab-supply', sizes: ['pack of 10'] },
]

export const FULL_CATALOGUE: CatalogueEntry[] = [...PEPTIDE_CATALOGUE, ...LAB_SUPPLY_CATALOGUE]
