// GENERATED by tools/product-shots/build.py, do not edit by hand.
// Sizes that have a product image at /products/<slug>-<size>.webp.
export const PRODUCT_IMAGE_SIZES: Record<string, string[]> = {
  'bpc-157': ['5mg', '10mg'],
  'tb-500': ['2mg', '5mg'],
  'ghk-cu': ['50mg'],
  'cjc-1295-no-dac': ['5mg'],
  'ipamorelin': ['5mg'],
  'sermorelin': ['5mg'],
  'tesamorelin': ['2mg', '10mg'],
  'igf-1-lr3': ['1mg'],
  'mots-c': ['10mg'],
  'nad-plus': ['500mg'],
  'epitalon': ['10mg'],
  'selank': ['5mg'],
  'semax': ['5mg'],
  'dsip': ['5mg'],
  'thymosin-alpha-1': ['5mg'],
  'pt-141': ['10mg'],
}
